#Liam Durkan 25/09/2023
#Compiles helloThreads 

CC=g++
CFLAGS= -std=c++11 -pthread

SIMPLE: helloThreads.cpp
	g++ -std=c++11 -pthread -o myProgram helloThreads.cpp Semaphore.cpp

CLEAN:
	rm myProgram *.o